### ISSUE TITLE
Random behavior while running the examples simulations

### ISSUE THREAD

**Issue by igs3000** [hust-diangroup/ns3-ai#50]
Dear ns3-ai developers,

1. I tried to install ns3-ai Model ns-3.35 under Debian linux (Native Install).
2. Further, I tried to install it in ns-3.33 under chroot jail (virtualization).

In both cased, I successfully installed it.
But, while trying to run the example scripts, the behavior is very random.

For example, if I try to run the a_plus_b example as follows:
```
$ cp -r contrib/ns3-ai/example/a_plus_b scratch/
$ cd scratch/a_plus_b/
$ python3 run.py
```

- Sometimes it is running and producing output. (I mean the Python code able to the ns-3 simulation and interact with it and producing outputs)
- But sometimes, it just hangs after displaying the string  **"build"**
- Sometimes it ends with some strange python related errors.
- I see a lot of CPU activity with no outputs

If I check the running processes using the command 
`$ ps -A`
It shows lot of running processes related with this python script and the ns-3 simulation code.

**Solution## that I found for running a_plus_b:**
run the python script in background
`$ python3 run.py`
and then run the c++ ns-3 simulation code
`./waf --run a_plus_b`
Now the simulation is working.

The other AI/ML based examples such as rl_rcp are failing in the same way most of the time. 

In that case also
- Sometimes it is running and producing output. (I mean the Python code able to the ns-3 simulation and interact with it and producing outputs)
- But sometimes, it just hangs after displaying the string  **"build"**
- Sometimes it ends with some strange python related errors.
- I see a lot of CPU activity with no outputs

**The solution## that I found for running a_plus_b is not at all working for rl_tcp and other real AI/ML simulations.**

Here I presented my Installation and testing procedure.(Here I only showed the examples that worked).
[Installing ns3-ai Model under ns-3.35](https://www.projectguideline.com/installing-ns3-ai-model-under-ns-3-35/)
[Installing ns3-ai Model under “chroot Jail”](https://www.projectguideline.com/installing-ns3-ai-model-under-chroot-jail/)

Charles Pandian

**Comment by Mauriyin** [comment]
Hi,
Thank you for your detailed comments. Here I think if you re-build ns-3 before running the python script? If you changed the files but didn't run "./waf" first (rebuild), it could take a very long time for ns3-ai to build (since it may only use one thread).
Regards,
Hao

**Comment by igs3000** [comment]
> Hi, Thank you for your detailed comments. Here I think if you re-build ns-3 before running the python script? If you changed the files but didn't run "./waf" first (rebuild), it could take a very long time for ns3-ai to build (since it may only use one thread). Regards, Hao
I have tested it with two different installations:
[Installing ns3-ai Model under ns-3.35](https://www.projectguideline.com/installing-ns3-ai-model-under-ns-3-35/)
[Installing ns3-ai Model under “chroot Jail”](https://www.projectguideline.com/installing-ns3-ai-model-under-chroot-jail/)

I am getting different errors in these two different installations.

For your information, I am running the default examples only.

./waf Build was successful

a_plus_b is running good (most of my trials)

```
root@AsusK55:/home/ms-van3t/scratch# cd a_plus_b/
root@AsusK55:/home/ms-van3t/scratch/a_plus_b# python3 run.py 
build
7+10=17
8+6=14
6+10=16
7+10=17
5+2=7
3+2=5
0+8=8
3+9=12
7+4=11
5+0=5
cleaning
```
But, I am getting strange errors while running rl-tcp.
(In fact, it was run successfully one time. but after that it is generating pyinterface related errors or strange errors like the following:

```
root@AsusK55:/home/ms-van3t/scratch# cd rl-tcp/
root@AsusK55:/home/ms-van3t/scratch/rl-tcp#  python3 run_rl_tcp.py  --use_rl --result
build
Traceback (most recent call last):
  File "run_rl_tcp.py", line 189, in <module>
    int(max(1, (segmentSize * segmentSize) / cWnd))
ZeroDivisionError: division by zero
cleaning
Exception ignored in: <function Experiment.__del__ at 0x7f4ee3a6c510>
Traceback (most recent call last):
  File "/root/.local/lib/python3.7/site-packages/py_interface.py", line 262, in __del__
  File "/root/.local/lib/python3.7/site-packages/py_interface.py", line 279, in kill
  File "/root/.local/lib/python3.7/site-packages/ns3_util.py", line 66, in kill_proc_tree
  File "/root/.local/lib/python3.7/site-packages/psutil/__init__.py", line 343, in __init__
  File "/root/.local/lib/python3.7/site-packages/psutil/__init__.py", line 365, in _init
  File "/root/.local/lib/python3.7/site-packages/psutil/_pslinux.py", line 1538, in __init__
  File "/root/.local/lib/python3.7/site-packages/psutil/_common.py", line 752, in get_procfs_path
KeyError: ('psutil',)
root@AsusK55:/home/ms-van3t/scratch/rl-tcp# sudo apt install  psutil
bash: sudo: command not found
root@AsusK55:/home/ms-van3t/scratch/rl-tcp# apt install  psutil
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package psutil

root@AsusK55:/home/ms-van3t/scratch/rl-tcp# pip3 install psutil
Requirement already satisfied: psutil in /root/.local/lib/python3.7/site-packages (5.7.2)


```

**Comment by edward1995-sha** [comment]
I came across the same problem. after building there is a ZeroDivisionError.

I run this rl_tcp example, I also  got stuck in **build** phase.

**Comment by Zhu-Yufeng** [comment]
> > Hi, Thank you for your detailed comments. Here I think if you re-build ns-3 before running the python script? If you changed the files but didn't run "./waf" first (rebuild), it could take a very long time for ns3-ai to build (since it may only use one thread). Regards, Hao
> > I have tested it with two different installations:
> > [Installing ns3-ai Model under ns-3.35](https://www.projectguideline.com/installing-ns3-ai-model-under-ns-3-35/)
> > [Installing ns3-ai Model under “chroot Jail”](https://www.projectguideline.com/installing-ns3-ai-model-under-chroot-jail/)
> 
> I am getting different errors in these two different installations.
> 
> For your information, I am running the default examples only.
> 
> ./waf Build was successful
> 
> a_plus_b is running good (most of my trials)
> 
> ```
> root@AsusK55:/home/ms-van3t/scratch# cd a_plus_b/
> root@AsusK55:/home/ms-van3t/scratch/a_plus_b# python3 run.py 
> build
> 7+10=17
> 8+6=14
> 6+10=16
> 7+10=17
> 5+2=7
> 3+2=5
> 0+8=8
> 3+9=12
> 7+4=11
> 5+0=5
> cleaning
> ```
> 
> But, I am getting strange errors while running rl-tcp. (In fact, it was run successfully one time. but after that it is generating pyinterface related errors or strange errors like the following:
> 
> ```
> root@AsusK55:/home/ms-van3t/scratch# cd rl-tcp/
> root@AsusK55:/home/ms-van3t/scratch/rl-tcp#  python3 run_rl_tcp.py  --use_rl --result
> build
> Traceback (most recent call last):
>   File "run_rl_tcp.py", line 189, in <module>
>     int(max(1, (segmentSize * segmentSize) / cWnd))
> ZeroDivisionError: division by zero
> cleaning
> Exception ignored in: <function Experiment.__del__ at 0x7f4ee3a6c510>
> Traceback (most recent call last):
>   File "/root/.local/lib/python3.7/site-packages/py_interface.py", line 262, in __del__
>   File "/root/.local/lib/python3.7/site-packages/py_interface.py", line 279, in kill
>   File "/root/.local/lib/python3.7/site-packages/ns3_util.py", line 66, in kill_proc_tree
>   File "/root/.local/lib/python3.7/site-packages/psutil/__init__.py", line 343, in __init__
>   File "/root/.local/lib/python3.7/site-packages/psutil/__init__.py", line 365, in _init
>   File "/root/.local/lib/python3.7/site-packages/psutil/_pslinux.py", line 1538, in __init__
>   File "/root/.local/lib/python3.7/site-packages/psutil/_common.py", line 752, in get_procfs_path
> KeyError: ('psutil',)
> root@AsusK55:/home/ms-van3t/scratch/rl-tcp# sudo apt install  psutil
> bash: sudo: command not found
> root@AsusK55:/home/ms-van3t/scratch/rl-tcp# apt install  psutil
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> E: Unable to locate package psutil
> 
> root@AsusK55:/home/ms-van3t/scratch/rl-tcp# pip3 install psutil
> Requirement already satisfied: psutil in /root/.local/lib/python3.7/site-packages (5.7.2)
> ```

I came across the same problem.     help me!!!

**Comment by Mauriyin** [comment]
Hi guys,
Thanks a lot for your patience. It seems that the 'show_output' option is set to 0 so there are no outputs. I pushed a new fix [here](https://github.com/hust-diangroup/ns3-ai/commit/3a8d6b8493956baa2a25408be75c2d56da7ce710) and please try this out! Thank you!
Regards,
Hao

**Comment by kant1999** [comment]
> > > Hi, Thank you for your detailed comments. Here I think if you re-build ns-3 before running the python script? If you changed the files but didn't run "./waf" first (rebuild), it could take a very long time for ns3-ai to build (since it may only use one thread). Regards, Hao
> > > I have tested it with two different installations:
> > > [Installing ns3-ai Model under ns-3.35](https://www.projectguideline.com/installing-ns3-ai-model-under-ns-3-35/)
> > > [Installing ns3-ai Model under “chroot Jail”](https://www.projectguideline.com/installing-ns3-ai-model-under-chroot-jail/)
> > 
> > 
> > I am getting different errors in these two different installations.
> > For your information, I am running the default examples only.
> > ./waf Build was successful
> > a_plus_b is running good (most of my trials)
> > ```
> > root@AsusK55:/home/ms-van3t/scratch# cd a_plus_b/
> > root@AsusK55:/home/ms-van3t/scratch/a_plus_b# python3 run.py 
> > build
> > 7+10=17
> > 8+6=14
> > 6+10=16
> > 7+10=17
> > 5+2=7
> > 3+2=5
> > 0+8=8
> > 3+9=12
> > 7+4=11
> > 5+0=5
> > cleaning
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > But, I am getting strange errors while running rl-tcp. (In fact, it was run successfully one time. but after that it is generating pyinterface related errors or strange errors like the following:
> > ```
> > root@AsusK55:/home/ms-van3t/scratch# cd rl-tcp/
> > root@AsusK55:/home/ms-van3t/scratch/rl-tcp#  python3 run_rl_tcp.py  --use_rl --result
> > build
> > Traceback (most recent call last):
> >   File "run_rl_tcp.py", line 189, in <module>
> >     int(max(1, (segmentSize * segmentSize) / cWnd))
> > ZeroDivisionError: division by zero
> > cleaning
> > Exception ignored in: <function Experiment.__del__ at 0x7f4ee3a6c510>
> > Traceback (most recent call last):
> >   File "/root/.local/lib/python3.7/site-packages/py_interface.py", line 262, in __del__
> >   File "/root/.local/lib/python3.7/site-packages/py_interface.py", line 279, in kill
> >   File "/root/.local/lib/python3.7/site-packages/ns3_util.py", line 66, in kill_proc_tree
> >   File "/root/.local/lib/python3.7/site-packages/psutil/__init__.py", line 343, in __init__
> >   File "/root/.local/lib/python3.7/site-packages/psutil/__init__.py", line 365, in _init
> >   File "/root/.local/lib/python3.7/site-packages/psutil/_pslinux.py", line 1538, in __init__
> >   File "/root/.local/lib/python3.7/site-packages/psutil/_common.py", line 752, in get_procfs_path
> > KeyError: ('psutil',)
> > root@AsusK55:/home/ms-van3t/scratch/rl-tcp# sudo apt install  psutil
> > bash: sudo: command not found
> > root@AsusK55:/home/ms-van3t/scratch/rl-tcp# apt install  psutil
> > Reading package lists... Done
> > Building dependency tree       
> > Reading state information... Done
> > E: Unable to locate package psutil
> > 
> > root@AsusK55:/home/ms-van3t/scratch/rl-tcp# pip3 install psutil
> > Requirement already satisfied: psutil in /root/.local/lib/python3.7/site-packages (5.7.2)
> > ```
> 
> I came across the same problem. help me!!!

解决了吗？相同的问题

**Comment by gugugu-eng** [comment]
我有相同的问题
root@AsusK55:/home/ms-van3t/scratch/rl-tcp#  python3 run_rl_tcp.py  --use_rl --result
build
Traceback (most recent call last):
  File "run_rl_tcp.py", line 189, in <module>
    int(max(1, (segmentSize * segmentSize) / cWnd))
ZeroDivisionError: division by zero
cleaning
Exception ignored in: <function Experiment.__del__ at 0x7f4ee3a6c510>
Traceback (most recent call last):
  File "/root/.local/lib/python3.7/site-packages/py_interface.py", line 262, in __del__
  File "/root/.local/lib/python3.7/site-packages/py_interface.py", line 279, in kill
  File "/root/.local/lib/python3.7/site-packages/ns3_util.py", line 66, in kill_proc_tree
  File "/root/.local/lib/python3.7/site-packages/psutil/__init__.py", line 343, in __init__
  File "/root/.local/lib/python3.7/site-packages/psutil/__init__.py", line 365, in _init
  File "/root/.local/lib/python3.7/site-packages/psutil/_pslinux.py", line 1538, in __init__
  File "/root/.local/lib/python3.7/site-packages/psutil/_common.py", line 752, in get_procfs_path
KeyError: ('psutil',)
root@AsusK55:/home/ms-van3t/scratch/rl-tcp# sudo apt install  psutil
bash: sudo: command not found
root@AsusK55:/home/ms-van3t/scratch/rl-tcp# apt install  psutil
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package psutil

root@AsusK55:/home/ms-van3t/scratch/rl-tcp# pip3 install psutil
Requirement already satisfied: psutil in /root/.local/lib/python3.7/site-packages (5.7.2)

请问大家解决了吗

**Comment by Mauriyin** [comment]
Hi guys,
Could you try to apply [this ](https://github.com/hust-diangroup/ns3-ai/commit/3a8d6b8493956baa2a25408be75c2d56da7ce710) for a fix?
